simplify bw unlock command

diff --git a/bwmenu b/bwmenu
--- a/bwmenu
+++ b/bwmenu
@@ -50,7 +50,7 @@ source "$DIR/lib-bwmenu"
 
 ask_password() {
   mpw=$(printf '' | rofi -dmenu -p "Master Password" -password -l 0 ${ROFI_OPTIONS[@]}) || exit $?
-  echo "$mpw" | bw unlock 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/' || exit_error $? "Could not unlock vault"
+  echo "$mpw" | bw unlock --raw || exit_error $? "Could not unlock vault"
 }
 
 get_session_key() {
@@ -495,6 +495,6 @@ parse_cli_arguments "$@"
 
 get_session_key
 select_autotype_command
-select_copy_command
-load_items
-show_items
+# select_copy_command
+# load_items
+# show_items
